spring.datasource.url=jdbc:postgresql://localhost:5432/lims
spring.datasource.username=postgres
spring.datasource.password=Amiaditya811@@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081